#!/usr/bin/env node
/**
 * Blitz Icons — codegen pipeline
 * Created by Blitz · https://t.me/blitz_core
 *
 * Reads raw SVG sources from packages/icons-svg/src/<category>/*.svg,
 * optimizes each with SVGO, parses it into an AST, and emits:
 *   - one TSX component per icon (packages/icons-react/src/icons/*.tsx)
 *   - a barrel file (packages/icons-react/src/index.ts)
 *   - icon metadata (packages/icons-svg/meta.json) consumed by the docs site
 *
 * This script is the single source of truth for scaling from tens of
 * icons today to 10,000+ icons later: adding an icon is just adding
 * one .svg file under icons-svg/src/<category>/ and re-running this.
 */
import { readdirSync, statSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { optimize } from "svgo";
import { parse } from "svgson";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../../..");
const SRC_DIR = path.join(ROOT, "packages/icons-svg/src");
const OUT_DIR = path.join(ROOT, "packages/icons-react/src/icons");
const INDEX_FILE = path.join(ROOT, "packages/icons-react/src/index.ts");
const META_FILE = path.join(ROOT, "packages/icons-svg/meta.json");

const PREFIX = "Bi"; // Blitz Icons component prefix

const svgoConfig = {
  multipass: true,
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          removeViewBox: false,
          convertPathData: { floatPrecision: 2 },
        },
      },
    },
    "removeDimensions",
    "removeXMLNS",
    { name: "removeAttrs", params: { attrs: "(data-name|id)" } },
  ],
};

function toPascalCase(str) {
  return str
    .split(/[-_ ]/g)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function attrsToObjectLiteral(attrs) {
  const camelMap = {
    "stroke-width": "strokeWidth",
    "stroke-linecap": "strokeLinecap",
    "stroke-linejoin": "strokeLinejoin",
    "stroke-dasharray": "strokeDasharray",
    "fill-rule": "fillRule",
    "clip-rule": "clipRule",
  };
  const entries = Object.entries(attrs || {})
    .filter(([k, v]) => {
      if (k === "stroke-width") return false; // inherit from root <svg> via strokeWidth prop
      if (k === "stroke" && v === "currentColor") return false; // inherit from root
      return true;
    })
    .map(([k, v]) => {
      const key = camelMap[k] || k;
      return `${JSON.stringify(key)}: ${JSON.stringify(v)}`;
    });
  return `{ ${entries.join(", ")} }`;
}

function nodeToTreeLiteral(node) {
  const children = (node.children || [])
    .filter((c) => c.type === "element")
    .map(nodeToTreeLiteral);
  return `{ tag: ${JSON.stringify(node.name)}, attr: ${attrsToObjectLiteral(node.attributes)}${
    children.length ? `, child: [${children.join(", ")}]` : ""
  } }`;
}

async function main() {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const categories = readdirSync(SRC_DIR).filter((f) =>
    statSync(path.join(SRC_DIR, f)).isDirectory()
  );

  const exportLines = [];
  const meta = [];
  let count = 0;

  for (const category of categories) {
    const dir = path.join(SRC_DIR, category);
    const files = readdirSync(dir).filter((f) => f.endsWith(".svg"));

    for (const file of files) {
      // eslint-disable-next-line no-await-in-loop
      const baseName = file.replace(/\.svg$/, "");
      const componentName = `${PREFIX}${toPascalCase(baseName)}`;
      const raw = readFileSync(path.join(dir, file), "utf8");
      const optimized = optimize(raw, { ...svgoConfig, path: file }).data;
      const ast = await parse(optimized);
      const svgRoot = ast.name === "svg" ? ast : (ast.children || []).find((c) => c.name === "svg") || ast;
      const treeChildren = (svgRoot.children || [])
        .filter((c) => c.type === "element")
        .map(nodeToTreeLiteral);

      const componentSrc = `// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/${category}/${file}
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const ${componentName} = buildIcon(${JSON.stringify(componentName)}, [${treeChildren.join(", ")}]);
export type ${componentName}Props = BlitzIconProps;
`;
      writeFileSync(path.join(OUT_DIR, `${componentName}.tsx`), componentSrc);
      exportLines.push(`export { ${componentName} } from "./icons/${componentName}";`);
      meta.push({ name: componentName, iconName: baseName, category });
      count++;
    }
  }

  exportLines.sort();
  const indexSrc = `// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Blitz Icons — Created by Blitz · Telegram: @blitz_core
export type { BlitzIconProps } from "./IconBase";

${exportLines.join("\n")}
`;
  writeFileSync(INDEX_FILE, indexSrc);
  writeFileSync(META_FILE, JSON.stringify(meta, null, 2));

  console.log(`Blitz Icons: generated ${count} components across ${categories.length} categories.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
