// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/api.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiApi = buildIcon("BiApi", [{ tag: "rect", attr: { "width": "6", "height": "5", "x": "3", "y": "9.5", "rx": "1.3" } }, { tag: "rect", attr: { "width": "6", "height": "5", "x": "15", "y": "9.5", "rx": "1.3" } }, { tag: "path", attr: { "strokeDasharray": "1.5 2.2", "strokeLinecap": "round", "d": "M9 12h6" } }]);
export type BiApiProps = BlitzIconProps;
