// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/arrow-up.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiArrowUp = buildIcon("BiArrowUp", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 19.5V5m-6 5.5L12 5l6 5.5" } }]);
export type BiArrowUpProps = BlitzIconProps;
