// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/arrow-left.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiArrowLeft = buildIcon("BiArrowLeft", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M19.5 12H5m5.5-6L5 12l5.5 6" } }]);
export type BiArrowLeftProps = BlitzIconProps;
