// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/arrow-right.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiArrowRight = buildIcon("BiArrowRight", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M4.5 12H19m-5.5-6 5.5 6-5.5 6" } }]);
export type BiArrowRightProps = BlitzIconProps;
