// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/arrow-up-right.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiArrowUpRight = buildIcon("BiArrowUpRight", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m6.5 17.5 11-11m-9-.5h9v9" } }]);
export type BiArrowUpRightProps = BlitzIconProps;
