// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/arrow-down.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiArrowDown = buildIcon("BiArrowDown", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 4.5V19m6-5.5L12 19l-6-5.5" } }]);
export type BiArrowDownProps = BlitzIconProps;
