// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/bell.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiBell = buildIcon("BiBell", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M6 10.5a6 6 0 1 1 12 0c0 4 1.5 5.5 1.5 5.5h-15S6 14.5 6 10.5M9.5 19a2.5 2.5 0 0 0 5 0" } }]);
export type BiBellProps = BlitzIconProps;
