// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/bolt.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiBolt = buildIcon("BiBolt", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M12.5 3 6 13.5h5L10 21l8-11h-5l.5-7Z" } }]);
export type BiBoltProps = BlitzIconProps;
