// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/bookmark.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiBookmark = buildIcon("BiBookmark", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M6.5 3.5h11a1 1 0 0 1 1 1V21L12 17l-6.5 4V4.5a1 1 0 0 1 1-1Z" } }]);
export type BiBookmarkProps = BlitzIconProps;
