// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/ai/brain.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiBrain = buildIcon("BiBrain", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M9.5 4.5a3 3 0 0 0-3 3v.3a3 3 0 0 0-2 2.8 3 3 0 0 0 1.3 2.5A3 3 0 0 0 6 15a3 3 0 0 0 3 3h.5zm5 0a3 3 0 0 1 3 3v.3a3 3 0 0 1 2 2.8 3 3 0 0 1-1.3 2.5A3 3 0 0 1 18 15a3 3 0 0 1-3 3h-.5z" } }]);
export type BiBrainProps = BlitzIconProps;
