// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/bug.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiBug = buildIcon("BiBug", [{ tag: "rect", attr: { "width": "8", "height": "9.5", "x": "8", "y": "8.5", "rx": "4" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M9 9 7.2 7M15 9l1.8-2M4.5 11h2.7m-2.7 4h2.7m12.3-4h-2.7m2.7 4h-2.7M9.5 5.5a2.5 2.5 0 0 1 5 0" } }]);
export type BiBugProps = BlitzIconProps;
