// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/calendar.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCalendar = buildIcon("BiCalendar", [{ tag: "rect", attr: { "width": "17", "height": "15.5", "x": "3.5", "y": "5", "rx": "2" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M3.5 9.5h17M8 3v3.5M16 3v3.5" } }]);
export type BiCalendarProps = BlitzIconProps;
