// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/commerce/cart.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCart = buildIcon("BiCart", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M3.5 4.5h2.2l1.1 11a2 2 0 0 0 2 1.8h7.9a2 2 0 0 0 2-1.7L19.8 8H6" } }, { tag: "circle", attr: { "cx": "9.5", "cy": "20", "r": "1.3", "fill": "currentColor" } }, { tag: "circle", attr: { "cx": "16.5", "cy": "20", "r": "1.3", "fill": "currentColor" } }]);
export type BiCartProps = BlitzIconProps;
