// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/camera.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCamera = buildIcon("BiCamera", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M4 8.3A1.3 1.3 0 0 1 5.3 7h2.4l1-1.7a1.3 1.3 0 0 1 1.1-.7h4.4a1.3 1.3 0 0 1 1.1.6l1 1.7h2.4A1.3 1.3 0 0 1 20 8.3v9.4a1.3 1.3 0 0 1-1.3 1.3H5.3A1.3 1.3 0 0 1 4 17.7z" } }, { tag: "circle", attr: { "cx": "12", "cy": "13", "r": "3.3" } }]);
export type BiCameraProps = BlitzIconProps;
