// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/chevron-down.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiChevronDown = buildIcon("BiChevronDown", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m5.5 9 6.5 6.5L18.5 9" } }]);
export type BiChevronDownProps = BlitzIconProps;
