// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/ai/chip-ai.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiChipAi = buildIcon("BiChipAi", [{ tag: "rect", attr: { "width": "12", "height": "12", "x": "6", "y": "6", "rx": "2.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m9.5 10.5 2 3 2-3" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M9 3v2.2M15 3v2.2M9 18.8V21m6-2.2V21M3 9h2.2M3 15h2.2m13.6-6H21m-2.2 6H21" } }]);
export type BiChipAiProps = BlitzIconProps;
