// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/check.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCheck = buildIcon("BiCheck", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m4.5 12.5 5 5L19.5 7" } }]);
export type BiCheckProps = BlitzIconProps;
