// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/chevron-right.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiChevronRight = buildIcon("BiChevronRight", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m9 5.5 6.5 6.5L9 18.5" } }]);
export type BiChevronRightProps = BlitzIconProps;
