// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/clock.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiClock = buildIcon("BiClock", [{ tag: "circle", attr: { "cx": "12", "cy": "12", "r": "8.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 7.5V12l3.2 2" } }]);
export type BiClockProps = BlitzIconProps;
