// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/cloud.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCloud = buildIcon("BiCloud", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M7 18.5a4.5 4.5 0 0 1-.5-9 5.5 5.5 0 0 1 10.7-1.8 4.5 4.5 0 0 1-.2 10.8z" } }]);
export type BiCloudProps = BlitzIconProps;
