// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/close.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiClose = buildIcon("BiClose", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m6 6 12 12m0-12L6 18" } }]);
export type BiCloseProps = BlitzIconProps;
