// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/copy.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCopy = buildIcon("BiCopy", [{ tag: "rect", attr: { "width": "11", "height": "11", "x": "8.5", "y": "8.5", "rx": "2" } }, { tag: "path", attr: { "strokeLinejoin": "round", "d": "M15.5 8.5V6A1.5 1.5 0 0 0 14 4.5H6A1.5 1.5 0 0 0 4.5 6v8A1.5 1.5 0 0 0 6 15.5h2.5" } }]);
export type BiCopyProps = BlitzIconProps;
