// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/container.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiContainer = buildIcon("BiContainer", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 8.5 12 4l8.5 4.5L12 13z" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M3.5 8.5V16l8.5 4.5V13m8.5-4.5V16L12 20.5" } }]);
export type BiContainerProps = BlitzIconProps;
