// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/code.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCode = buildIcon("BiCode", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M9 6.5 3.5 12 9 17.5m6-11 5.5 5.5-5.5 5.5" } }]);
export type BiCodeProps = BlitzIconProps;
