// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/corner-up.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCornerUp = buildIcon("BiCornerUp", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M5 19v-6a4 4 0 0 1 4-4h10m-6-4.5L19 9l-6 4.5" } }]);
export type BiCornerUpProps = BlitzIconProps;
