// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/cpu.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCpu = buildIcon("BiCpu", [{ tag: "rect", attr: { "width": "10", "height": "10", "x": "7", "y": "7", "rx": "1.5" } }, { tag: "rect", attr: { "width": "4", "height": "4", "x": "10", "y": "10", "rx": ".8" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M9.5 2.5v3m5-3v3m-5 13v3m5-3v3m-12-12h3m-3 5h3m13-5h3m-3 5h3" } }]);
export type BiCpuProps = BlitzIconProps;
