// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/commerce/credit-card.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiCreditCard = buildIcon("BiCreditCard", [{ tag: "rect", attr: { "width": "19", "height": "13", "x": "2.5", "y": "5.5", "rx": "2.2" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M2.5 9.5h19M6 14.5h4" } }]);
export type BiCreditCardProps = BlitzIconProps;
