// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/database.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiDatabase = buildIcon("BiDatabase", [{ tag: "ellipse", attr: { "cx": "12", "cy": "6", "rx": "7.5", "ry": "3" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M4.5 6v6c0 1.7 3.4 3 7.5 3s7.5-1.3 7.5-3V6" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M4.5 12v6c0 1.7 3.4 3 7.5 3s7.5-1.3 7.5-3v-6" } }]);
export type BiDatabaseProps = BlitzIconProps;
