// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/download.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiDownload = buildIcon("BiDownload", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 3.5V15m-5-4 5 5 5-5M4.5 17v2.2a1 1 0 0 0 1 1h13a1 1 0 0 0 1-1V17" } }]);
export type BiDownloadProps = BlitzIconProps;
