// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/edit.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiEdit = buildIcon("BiEdit", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m14.5 4.5 5 5L8 21H3.5v-4.5z" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "m12.5 6.5 5 5" } }]);
export type BiEditProps = BlitzIconProps;
