// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/eye.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiEye = buildIcon("BiEye", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M2.5 12S6 5.5 12 5.5s9.5 6.5 9.5 6.5-3.5 6.5-9.5 6.5S2.5 12 2.5 12" } }, { tag: "circle", attr: { "cx": "12", "cy": "12", "r": "3" } }]);
export type BiEyeProps = BlitzIconProps;
