// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/eye-off.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiEyeOff = buildIcon("BiEyeOff", [{ tag: "path", attr: { "strokeLinecap": "round", "d": "m4 4 16 16" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M9.9 5.7c.7-.1 1.4-.2 2.1-.2 6 0 9.5 6.5 9.5 6.5s-1.1 2-3.1 3.7M6.6 7.3C4.2 8.9 2.5 12 2.5 12S6 18.5 12 18.5c1.1 0 2.1-.2 3-.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M9.9 10c-.3.5-.4 1-.4 1.6a2.5 2.5 0 0 0 3.6 2.2" } }]);
export type BiEyeOffProps = BlitzIconProps;
