// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/filter.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFilter = buildIcon("BiFilter", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 5h17L14 12.5v6L10 21v-8.5z" } }]);
export type BiFilterProps = BlitzIconProps;
