// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/file-code.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFileCode = buildIcon("BiFileCode", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M6.5 3.5h8l4 4.5v11.7a.8.8 0 0 1-.8.8H6.5a.8.8 0 0 1-.8-.8V4.3a.8.8 0 0 1 .8-.8Z" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M14.5 3.5V8h4m-8.7 4.2L8 14l1.8 1.8m4.4-3.6L16 14l-1.8 1.8" } }]);
export type BiFileCodeProps = BlitzIconProps;
