// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/security/fingerprint.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFingerprint = buildIcon("BiFingerprint", [{ tag: "path", attr: { "strokeLinecap": "round", "d": "M12 3.5a8.5 8.5 0 0 1 8.5 8.5v2.5M12 3.5A8.5 8.5 0 0 0 3.5 12v1M8 20.5A8.4 8.4 0 0 1 5.5 15v-3a6.5 6.5 0 0 1 13 0v3" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M12 8.5A3.5 3.5 0 0 0 8.5 12v2a5.5 5.5 0 0 0 2.3 4.5m1.2-10a3.5 3.5 0 0 1 3.5 3.5v3a5.5 5.5 0 0 1-1 3.2M12 12v3.2" } }]);
export type BiFingerprintProps = BlitzIconProps;
