// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/file-text.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFileText = buildIcon("BiFileText", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M6.5 3.5h8l4 4.5v11.7a.8.8 0 0 1-.8.8H6.5a.8.8 0 0 1-.8-.8V4.3a.8.8 0 0 1 .8-.8Z" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M14.5 3.5V8h4m-10 4.5h7m-7 3.5h5" } }]);
export type BiFileTextProps = BlitzIconProps;
