// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/folder.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFolder = buildIcon("BiFolder", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 6.3a.8.8 0 0 1 .8-.8h4.9l2 2.3h8a.8.8 0 0 1 .8.8v8.9a1.5 1.5 0 0 1-1.5 1.5H5a1.5 1.5 0 0 1-1.5-1.5z" } }]);
export type BiFolderProps = BlitzIconProps;
