// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/folder-open.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiFolderOpen = buildIcon("BiFolderOpen", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 8.3v-2a.8.8 0 0 1 .8-.8h4.9l2 2.3h8a.8.8 0 0 1 .8.8v1" } }, { tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 8.3h17l-1.7 8.9a1.5 1.5 0 0 1-1.5 1.2H6.7a1.5 1.5 0 0 1-1.5-1.2z" } }]);
export type BiFolderOpenProps = BlitzIconProps;
