// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/commerce/gift.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiGift = buildIcon("BiGift", [{ tag: "rect", attr: { "width": "17", "height": "4.5", "x": "3.5", "y": "9", "rx": "1" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M5.5 13.5v6a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-6M12 9v11.5" } }, { tag: "path", attr: { "strokeLinejoin": "round", "d": "M12 9c0-3-2.5-4.5-4-4.5S5.5 6 6.5 7.5 10.5 9 12 9Zm0 0c0-3 2.5-4.5 4-4.5s2.5 1.5 1.5 3S13.5 9 12 9Z" } }]);
export type BiGiftProps = BlitzIconProps;
