// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/git-branch.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiGitBranch = buildIcon("BiGitBranch", [{ tag: "circle", attr: { "cx": "6", "cy": "5", "r": "2" } }, { tag: "circle", attr: { "cx": "6", "cy": "19", "r": "2" } }, { tag: "circle", attr: { "cx": "18", "cy": "9", "r": "2" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M6 7v10m0-6a6 6 0 0 0 6 6h4m2-6V7" } }]);
export type BiGitBranchProps = BlitzIconProps;
