// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/globe.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiGlobe = buildIcon("BiGlobe", [{ tag: "circle", attr: { "cx": "12", "cy": "12", "r": "8.5" } }, { tag: "path", attr: { "d": "M3.5 12h17M12 3.5c2.4 2.2 3.7 5.2 3.7 8.5s-1.3 6.3-3.7 8.5c-2.4-2.2-3.7-5.2-3.7-8.5S9.6 5.7 12 3.5Z" } }]);
export type BiGlobeProps = BlitzIconProps;
