// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/grid.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiGrid = buildIcon("BiGrid", [{ tag: "rect", attr: { "width": "7.2", "height": "7.2", "x": "3.5", "y": "3.5", "rx": "1.8" } }, { tag: "rect", attr: { "width": "7.2", "height": "7.2", "x": "13.3", "y": "3.5", "rx": "1.8" } }, { tag: "rect", attr: { "width": "7.2", "height": "7.2", "x": "3.5", "y": "13.3", "rx": "1.8" } }, { tag: "rect", attr: { "width": "7.2", "height": "7.2", "x": "13.3", "y": "13.3", "rx": "1.8" } }]);
export type BiGridProps = BlitzIconProps;
