// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/heart.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiHeart = buildIcon("BiHeart", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M12 20s-7.5-4.6-9.7-9.4C.9 7 3 3.8 6.6 3.8c2 0 3.7 1.1 5.4 3 1.7-1.9 3.4-3 5.4-3 3.6 0 5.7 3.2 4.3 6.8C19.5 15.4 12 20 12 20Z" } }]);
export type BiHeartProps = BlitzIconProps;
