// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/image.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiImage = buildIcon("BiImage", [{ tag: "rect", attr: { "width": "17", "height": "15", "x": "3.5", "y": "4.5", "rx": "2" } }, { tag: "circle", attr: { "cx": "9", "cy": "10", "r": "1.6" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m4.5 17 4.7-4.7a1.5 1.5 0 0 1 2.1 0l1.4 1.4M14 15l1.9-1.9a1.5 1.5 0 0 1 2.1 0l1.5 1.5" } }]);
export type BiImageProps = BlitzIconProps;
