// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/security/key.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiKey = buildIcon("BiKey", [{ tag: "circle", attr: { "cx": "7.5", "cy": "15.5", "r": "4" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m10.3 12.8 8.2-8.3m-3 3 2.2 2.2M18 5l2.5 2.5" } }]);
export type BiKeyProps = BlitzIconProps;
