// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/layers.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiLayers = buildIcon("BiLayers", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M12 3.5 20.5 8 12 12.5 3.5 8z" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M3.5 12.5 12 17l8.5-4.5m-17 4L12 21l8.5-4.5" } }]);
export type BiLayersProps = BlitzIconProps;
