// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/logout.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiLogout = buildIcon("BiLogout", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M13 4.5h4.2a1.3 1.3 0 0 1 1.3 1.3v12.4a1.3 1.3 0 0 1-1.3 1.3H13M9 8l-4 4 4 4m5.5-4h-9" } }]);
export type BiLogoutProps = BlitzIconProps;
