// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/login.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiLogin = buildIcon("BiLogin", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M11 4.5H6.8a1.3 1.3 0 0 0-1.3 1.3v12.4a1.3 1.3 0 0 0 1.3 1.3H11M15 8l4 4-4 4m-5.5-4h9" } }]);
export type BiLoginProps = BlitzIconProps;
