// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/map-pin.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMapPin = buildIcon("BiMapPin", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M12 21s7-6.4 7-12A7 7 0 0 0 5 9c0 5.6 7 12 7 12Z" } }, { tag: "circle", attr: { "cx": "12", "cy": "9", "r": "2.5" } }]);
export type BiMapPinProps = BlitzIconProps;
