// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/communication/mail.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMail = buildIcon("BiMail", [{ tag: "rect", attr: { "width": "18", "height": "13", "x": "3", "y": "5.5", "rx": "2" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m4 7 8 6 8-6" } }]);
export type BiMailProps = BlitzIconProps;
