// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/menu.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMenu = buildIcon("BiMenu", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M4 6.5h16M4 12h12M4 17.5h16" } }]);
export type BiMenuProps = BlitzIconProps;
