// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/communication/message.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMessage = buildIcon("BiMessage", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 6.8a2.3 2.3 0 0 1 2.3-2.3h12.4a2.3 2.3 0 0 1 2.3 2.3v7.4a2.3 2.3 0 0 1-2.3 2.3H9l-5.5 4z" } }]);
export type BiMessageProps = BlitzIconProps;
