// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/minus.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMinus = buildIcon("BiMinus", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M4.5 12h15" } }]);
export type BiMinusProps = BlitzIconProps;
