// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/mic.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMic = buildIcon("BiMic", [{ tag: "rect", attr: { "width": "6", "height": "11", "x": "9", "y": "3", "rx": "3" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21m-3 0h6" } }]);
export type BiMicProps = BlitzIconProps;
