// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/moon.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiMoon = buildIcon("BiMoon", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M20 13.8A8.3 8.3 0 0 1 10.2 4a8.3 8.3 0 1 0 9.8 9.8Z" } }]);
export type BiMoonProps = BlitzIconProps;
