// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/pause.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiPause = buildIcon("BiPause", [{ tag: "rect", attr: { "width": "4", "height": "15", "x": "6.5", "y": "4.5", "rx": "1.2" } }, { tag: "rect", attr: { "width": "4", "height": "15", "x": "13.5", "y": "4.5", "rx": "1.2" } }]);
export type BiPauseProps = BlitzIconProps;
