// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/communication/phone.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiPhone = buildIcon("BiPhone", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M6 3.5h2.5l1.3 4.2-2 1.6a11.5 11.5 0 0 0 5.9 5.9l1.6-2 4.2 1.3V17a2 2 0 0 1-2 2C10.6 19 5 13.4 5 6.5a2 2 0 0 1 1-3Z" } }]);
export type BiPhoneProps = BlitzIconProps;
