// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/play.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiPlay = buildIcon("BiPlay", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M7 4.8v14.4a1 1 0 0 0 1.5.9L20 12.9a1 1 0 0 0 0-1.8L8.5 3.9a1 1 0 0 0-1.5.9Z" } }]);
export type BiPlayProps = BlitzIconProps;
