// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/plus.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiPlus = buildIcon("BiPlus", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 4.5v15M4.5 12h15" } }]);
export type BiPlusProps = BlitzIconProps;
