// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/refresh.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiRefresh = buildIcon("BiRefresh", [{ tag: "path", attr: { "strokeLinecap": "round", "d": "M20 12a8 8 0 1 1-2.7-6" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M20 5v5.5h-5.5" } }]);
export type BiRefreshProps = BlitzIconProps;
