// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/rocket.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiRocket = buildIcon("BiRocket", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M13.5 3.5c3 0 6 3 6 6-1.5 5-5 8-9.5 10-.8-2-1.5-3-3-4-1-1.5-2-2.2-4-3 2-4.5 5-8 10.5-9Z" } }, { tag: "circle", attr: { "cx": "14", "cy": "9.5", "r": "1.7" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M7 15.5c-2 .5-3 2.5-3.5 5C6 20 8 19 8.5 17" } }]);
export type BiRocketProps = BlitzIconProps;
