// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/ai/robot.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiRobot = buildIcon("BiRobot", [{ tag: "rect", attr: { "width": "14", "height": "10", "x": "5", "y": "9.5", "rx": "2.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M12 6.5v3m-2.5-6h5" } }, { tag: "circle", attr: { "cx": "9.3", "cy": "14", "r": "1.1", "fill": "currentColor" } }, { tag: "circle", attr: { "cx": "14.7", "cy": "14", "r": "1.1", "fill": "currentColor" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M2.5 12.5v3m19-3v3" } }]);
export type BiRobotProps = BlitzIconProps;
