// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/search.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSearch = buildIcon("BiSearch", [{ tag: "circle", attr: { "cx": "10.5", "cy": "10.5", "r": "6.5", "strokeLinecap": "round", "strokeLinejoin": "round" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m19.5 19.5-4.2-4.2" } }]);
export type BiSearchProps = BlitzIconProps;
