// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/server.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiServer = buildIcon("BiServer", [{ tag: "rect", attr: { "width": "17", "height": "6.5", "x": "3.5", "y": "4", "rx": "1.5" } }, { tag: "rect", attr: { "width": "17", "height": "6.5", "x": "3.5", "y": "13.5", "rx": "1.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M7 7.2h.01M7 16.7h.01" } }]);
export type BiServerProps = BlitzIconProps;
