// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/arrows/send.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSend = buildIcon("BiSend", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m20.5 3.5-9.8 9.8m9.8-9.8-6.5 17-3.3-7.2L3.5 10z" } }]);
export type BiSendProps = BlitzIconProps;
