// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/settings.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSettings = buildIcon("BiSettings", [{ tag: "circle", attr: { "cx": "12", "cy": "12", "r": "3", "strokeLinecap": "round", "strokeLinejoin": "round" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 3.5v2.4m0 12.2v2.4M4.6 7.2l2.1 1.2m10.6 7.2 2.1 1.2m-14.8 0 2.1-1.2m10.6-7.2 2.1-1.2M3.5 12h2.4m12.2 0h2.4" } }]);
export type BiSettingsProps = BlitzIconProps;
