// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/communication/share.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiShare = buildIcon("BiShare", [{ tag: "circle", attr: { "cx": "18", "cy": "5.5", "r": "2.3" } }, { tag: "circle", attr: { "cx": "6", "cy": "12", "r": "2.3" } }, { tag: "circle", attr: { "cx": "18", "cy": "18.5", "r": "2.3" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "m8.1 10.7 7.8-3.9m-7.8 6.5 7.8 3.9" } }]);
export type BiShareProps = BlitzIconProps;
