// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/security/shield.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiShield = buildIcon("BiShield", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "m12 3.5 7 2.6v6c0 4.5-3 7.5-7 8.9-4-1.4-7-4.4-7-8.9v-6z" } }]);
export type BiShieldProps = BlitzIconProps;
