// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/sliders.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSliders = buildIcon("BiSliders", [{ tag: "path", attr: { "strokeLinecap": "round", "d": "M5 6.5h14M5 12h14M5 17.5h14" } }, { tag: "circle", attr: { "cx": "9", "cy": "6.5", "r": "2", "fill": "var(--bi-bg,#fff)" } }, { tag: "circle", attr: { "cx": "16", "cy": "12", "r": "2", "fill": "var(--bi-bg,#fff)" } }, { tag: "circle", attr: { "cx": "10.5", "cy": "17.5", "r": "2", "fill": "var(--bi-bg,#fff)" } }]);
export type BiSlidersProps = BlitzIconProps;
