// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/ai/spark.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSpark = buildIcon("BiSpark", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "m12 3.5 1.8 5.3 5.2 1.7-5.2 1.7-1.8 5.3-1.8-5.3L5 10.5l5.2-1.7z" } }, { tag: "path", attr: { "strokeLinejoin": "round", "d": "m18.5 16.5.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8z" } }]);
export type BiSparkProps = BlitzIconProps;
