// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/star.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiStar = buildIcon("BiStar", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "m12 3.5 2.7 5.6 6.1.8-4.4 4.3 1 6.1-5.4-3-5.4 3 1-6.1-4.4-4.3 6.1-.8z" } }]);
export type BiStarProps = BlitzIconProps;
