// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/interface/sun.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiSun = buildIcon("BiSun", [{ tag: "circle", attr: { "cx": "12", "cy": "12", "r": "4" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M12 2.8v2.4m0 13.6v2.4M4.9 4.9l1.7 1.7m10.8 10.8 1.7 1.7M2.8 12h2.4m13.6 0h2.4M4.9 19.1l1.7-1.7M17.4 6.6l1.7-1.7" } }]);
export type BiSunProps = BlitzIconProps;
