// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/commerce/tag.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiTag = buildIcon("BiTag", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M11.6 3.5H6.3A1.3 1.3 0 0 0 5 4.8v5.3a1.3 1.3 0 0 0 .4.9l9 9a1.3 1.3 0 0 0 1.8 0l4.9-4.9a1.3 1.3 0 0 0 0-1.8l-9-9a1.3 1.3 0 0 0-.5-.3Z" } }, { tag: "circle", attr: { "cx": "9", "cy": "8.5", "r": "1.2", "fill": "currentColor" } }]);
export type BiTagProps = BlitzIconProps;
