// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/dev/terminal.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiTerminal = buildIcon("BiTerminal", [{ tag: "rect", attr: { "width": "18", "height": "15", "x": "3", "y": "4.5", "rx": "2" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m7 9.5 3 2.8-3 2.8m5.5.4H17" } }]);
export type BiTerminalProps = BlitzIconProps;
