// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/trash.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiTrash = buildIcon("BiTrash", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M4.5 7h15m-10 0V5A1.5 1.5 0 0 1 11 3.5h2A1.5 1.5 0 0 1 14.5 5v2m-8 0v12.2a1.3 1.3 0 0 0 1.3 1.3h8.4a1.3 1.3 0 0 0 1.3-1.3V7M10 11v6m4-6v6" } }]);
export type BiTrashProps = BlitzIconProps;
