// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/security/unlock.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUnlock = buildIcon("BiUnlock", [{ tag: "rect", attr: { "width": "15", "height": "9.5", "x": "4.5", "y": "10.5", "rx": "2" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M7.5 10.5V7.3a4.5 4.5 0 0 1 8.6-1.8" } }, { tag: "circle", attr: { "cx": "12", "cy": "15", "r": "1.4", "fill": "currentColor" } }]);
export type BiUnlockProps = BlitzIconProps;
