// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/files/upload.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUpload = buildIcon("BiUpload", [{ tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "M12 15.5V4M7 8l5-5 5 5M4.5 17v2.2a1 1 0 0 0 1 1h13a1 1 0 0 0 1-1V17" } }]);
export type BiUploadProps = BlitzIconProps;
