// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/user-check.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUserCheck = buildIcon("BiUserCheck", [{ tag: "circle", attr: { "cx": "10", "cy": "8", "r": "3.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M2.8 19.5a7.2 7.2 0 0 1 14.4 0" } }, { tag: "path", attr: { "strokeLinecap": "round", "strokeLinejoin": "round", "d": "m15.5 12 2 2 4-4" } }]);
export type BiUserCheckProps = BlitzIconProps;
