// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/user.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUser = buildIcon("BiUser", [{ tag: "circle", attr: { "cx": "12", "cy": "8", "r": "3.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M4.8 19.5a7.2 7.2 0 0 1 14.4 0" } }]);
export type BiUserProps = BlitzIconProps;
