// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/user-plus.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUserPlus = buildIcon("BiUserPlus", [{ tag: "circle", attr: { "cx": "10", "cy": "8", "r": "3.5" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M2.8 19.5a7.2 7.2 0 0 1 14.4 0M18.5 8v6m-3-3h6" } }]);
export type BiUserPlusProps = BlitzIconProps;
