// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/users/users.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiUsers = buildIcon("BiUsers", [{ tag: "circle", attr: { "cx": "9", "cy": "8", "r": "3.2" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M2.8 19a6.2 6.2 0 0 1 12.4 0m.3-13.8a3.2 3.2 0 0 1 0 6.1M18 13a6.2 6.2 0 0 1 3.2 5.4" } }]);
export type BiUsersProps = BlitzIconProps;
