// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/media/volume.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiVolume = buildIcon("BiVolume", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M4 9.5h3.3L12 5.8v12.4l-4.7-3.7H4z" } }, { tag: "path", attr: { "strokeLinecap": "round", "d": "M15.5 9a4 4 0 0 1 0 6m2.3-8.5a7.5 7.5 0 0 1 0 11" } }]);
export type BiVolumeProps = BlitzIconProps;
