// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/commerce/wallet.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiWallet = buildIcon("BiWallet", [{ tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 7.3a1.8 1.8 0 0 1 1.8-1.8h11.4a1.8 1.8 0 0 1 1.8 1.8V8H5.3a1.8 1.8 0 0 1-1.8-1.8Z" } }, { tag: "path", attr: { "strokeLinejoin": "round", "d": "M3.5 7.3v10A1.7 1.7 0 0 0 5.2 19h13.6a1.7 1.7 0 0 0 1.7-1.7v-8a1.7 1.7 0 0 0-1.7-1.7H5.2" } }, { tag: "circle", attr: { "cx": "16", "cy": "14", "r": "1.3", "fill": "currentColor" } }]);
export type BiWalletProps = BlitzIconProps;
