// Auto-generated by Blitz Icons build pipeline. Do not edit by hand.
// Source: packages/icons-svg/src/communication/wifi.svg
import { buildIcon, type BlitzIconProps } from "../IconBase";

export const BiWifi = buildIcon("BiWifi", [{ tag: "path", attr: { "strokeLinecap": "round", "d": "M4 9a11.5 11.5 0 0 1 16 0M7 12.3a7 7 0 0 1 10 0m-6.8 3.3a2.6 2.6 0 0 1 3.6 0" } }, { tag: "circle", attr: { "cx": "12", "cy": "19", "r": "1.1", "fill": "currentColor" } }]);
export type BiWifiProps = BlitzIconProps;
